### ISSUE TITLE
Cantidad 0 en devoluciones

### ISSUE THREAD

**Issue by JPCT** [cacuestai/salestore#4]
En devoluciones ventas y devoluciones compras al seleccionar un usuario con una venta carga que tiene cantidad de ventas o compras igual a 0 y este campo se deja modificar.

**Comment by cacuestai** [comment]
¡Buen punto! ... Se deben realizar los casos de prueba necesarios sobre **todas** las entradas de datos de todos los formularios y tablas, para evitar sorpresas a la hora de sustentar el proyecto. El prototipo **salestore** por ahora continuará con dichos bugs...
